---
# handlers file for ansible-lsyncd-cluster

# When you reload on centos/redhat it always comes back with a error.
- name: reload sysctl
  shell: sysctl -p
  ignore_errors: true
  notify: restart lsyncd
  
# This will restart lsyncd but only on the designated "master" node.
- name: restart lsyncd
  service:
    name: lsyncd
    state: restarted
  when: ansible_hostname.find('{{ lsyncd_master_node }}') != -1
